# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_createcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcomment',
            name='id',
        ),
        migrations.AlterField(
            model_name='createcomment',
            name='uf',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
