# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160629_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcomment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
